### ISSUE TITLE
No module named 'jep' on OSX

### ISSUE THREAD

**Issue by dportabella** [sushant-hiray/scala-python-example#3]
After importing the right JEP libraries for OSX, it still fails with "No module named 'jep'"

```
pip install jep
git clone https://github.com/sushant-hiray/scala-python-example.git
cd scala-python-example
rm -Rf lib
cp -r /Users/david/.virtualenvs/py3-data/lib/python3.6/site-packages/jep lib
sbt "runMain com.sushant.example.JepAddExample"
# java.lang.UnsatisfiedLinkError: no jep in java.library.path

# http://www.macworld.com/article/2986118/security/how-to-modify-system-integrity-protection-in-el-capitan.html
sudo cp lib/libjep.jnilib /Library/Java/Extensions/

sbt "runMain com.sushant.example.JepAddExample"
# jep.JepException: <class 'ModuleNotFoundError'>: No module named 'jep' 	at <string>.<module>(<string>:1)
```

Same result when running without sbt
```
sbt package
java -cp target/scala-2.10/scala-python-example_2.10-1.0.jar:/Users/david/.sbt/boot/scala-2.10.6/lib/scala-library.jar:./lib/jep-3.6.3.jar -Djava.library.path=./lib/ com.sushant.example.JepAddExample
# Exception in thread "main" jep.JepException: <class 'ModuleNotFoundError'>: No module named 'jep' 	at <string>.<module>(<string>:1)
```

Note: I see that the JEP library is being loaded, because inserting these two lines on the Scala file work (after following the above steps):
```
System.load("/tmp/scala-python-example/lib/libjep.jnilib")
System.loadLibrary("jep")
```

Any idea?

**Comment by sushant-hiray** [comment]
Hi,
Can you try setting `PYTHONHOME` environment variable pointing at the virtualenv directory?
Just saw someone facing similar issue here: https://github.com/mrj0/jep/issues/18

**Comment by dportabella** [comment]
Yes, this did solve the problem, thx! :)
`$ export PYTHONHOME=/Users/david/.virtualenvs/py3-data`

Do you know if is it possible to specify the `PYTHONHOME` in `build.sbt` or `JepAddExample.scala`?
I see that `Jep.java` has `JepConfig` and `PyConfig`, but I don't see such a `pythonHome` variable.

**Comment by sushant-hiray** [comment]
I don't think there is a way to set `PYTHONHOME` via `JepConfig`. As far as I know, the system environment variables are immutable in the current process the JVM is started. You can set them by forking a new process. Or pass them while starting `sbt`, which is as good as `export` you've done.

**Comment by dportabella** [comment]
thx!

**Comment by eugkhp** [comment]
@dportabella You could add env in build.sbt this way:
```
  .settings(envVars in Test := Map("PYTHONHOME" -> "/your/path/to/venv"))
```
